packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  lefthook: true
  spawn-sync: true

minimumReleaseAgeExclude:
  - '@tanstack/router-generator@1.167.21'
  - '@tanstack/router-plugin@1.168.22'

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - spawn-sync
